data:
  eval_database_files:  ['/home/demiao/bisheR/pickles/oxford/oxford_evaluation_database.pickle',
                        '/home/demiao/bishe/pickles/oxford/business_evaluation_database.pickle', 
                        '/home/demiao/bishe/pickles/oxford/residential_evaluation_database.pickle', 
                        '/home/demiao/bishe/pickles/oxford/university_evaluation_database.pickle']
  eval_query_files: ['/home/demiao/bishe/pickles/oxford/oxford_evaluation_query.pickle',
                    '/home/demiao/bishe/pickles/oxford/business_evaluation_query.pickle', 
                    '/home/demiao/bishe/pickles/oxford/residential_evaluation_query.pickle', 
                    '/home/demiao/bishe/pickles/oxford/university_evaluation_query.pickle']
  pin_memory: False
model:
  name: TransLoc3D
  backbone:
    in_channels: 1
    out_channels: 512
    up_convs:
      in_channels: [1,64]
      out_channels: [64,64]
      kernel_size: [5,2]
      stride: [1,2]
    transformer:
      num_attn_layers: 6
      global_channels: 64
      local_channels: 0
      num_centers: [256,128,128,64,64,64]
      num_heads: 2
  pooling:
    name: NetVlad
    in_channels: 512
    out_channels: 256
    cluster_size: 64
    gating: True
    add_bn: True
train:
  batch_size: 32
  batch_size_limit: 64
  optimizer:
    lr: 0.0002
    epochs: 80
    scheduler_milestones: [60]
eval:
  frequency: -1
  batch_size: 128
